# Generated by Django 2.2.1 on 2019-06-01 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trip', '0002_auto_20190420_1512'),
        ('user', '0002_auto_20190419_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tel_number', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('S', 'Отправлен'), ('A', 'Одобрен'), ('C', 'Не одобрен')], default='S', max_length=1)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal', to='user.Profile')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal', to='trip.Trip')),
            ],
        ),
    ]
