# Generated by Django 2.2.1 on 2019-05-23 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('S', 'Отправлен'), ('A', 'Одобрен'), ('C', 'Не одобрен')], default=None, max_length=1),
        ),
    ]
