# Generated by Django 2.1.5 on 2019-04-20 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='empty_seats',
            field=models.PositiveIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='trip',
            name='price',
            field=models.PositiveIntegerField(default=None),
        ),
    ]
